#--------- This file is automatically generated by LSST's sconsUtils ---------#
__version__ = 'unknown'
__repo_version__ = 'unknown'
__fingerprint__ = '9ccb437db1a6f99b6d463bd5bbecf6f7ae74771f *'
__dependency_versions__ = {
}
__all__ = ('__version__', '__repo_version__', '__fingerprint__', '__dependency_versions__')
